"""auto stage 11 to 18

Revision ID: 3685683c7679
Revises: 481a4fdab327
Create Date: 2026-08-16 20:55:46.538042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3685683c7679'
down_revision: Union[str, None] = '481a4fdab327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_code'), 'business_units', ['code'], unique=False)
    op.create_index(op.f('ix_business_units_tenant_id'), 'business_units', ['tenant_id'], unique=False)
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_tenant_id'), 'chart_of_accounts', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'REVERSED', name='journalstatus', native_enum=False), nullable=False),
    sa.Column('reversal_journal_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['reversal_journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_date'), 'journals', ['date'], unique=False)
    op.create_index(op.f('ix_journals_status'), 'journals', ['status'], unique=False)
    op.create_index(op.f('ix_journals_tenant_id'), 'journals', ['tenant_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chart_of_accounts_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype', native_enum=False), nullable=False),
    sa.Column('is_control_account', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['chart_of_accounts_id'], ['chart_of_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_code'), 'accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_chart_of_accounts_id'), 'accounts', ['chart_of_accounts_id'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_table('ap_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'PARTIAL', 'PAID', 'VOID', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('invoice_type', sa.Enum('STANDARD', 'CREDIT_NOTE', name='invoicetype', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_invoices_tenant_id'), 'ap_invoices', ['tenant_id'], unique=False)
    op.create_table('ar_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'POSTED', 'PARTIAL', 'PAID', 'VOID', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('invoice_type', sa.Enum('STANDARD', 'CREDIT_NOTE', name='invoicetype', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_invoices_tenant_id'), 'ar_invoices', ['tenant_id'], unique=False)
    op.create_table('ap_invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ap_invoice_lines_tenant_id'), 'ap_invoice_lines', ['tenant_id'], unique=False)
    op.create_table('ar_invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['ar_invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_invoice_lines_tenant_id'), 'ar_invoice_lines', ['tenant_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('gl_account_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['gl_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_tenant_id'), 'bank_accounts', ['tenant_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('business_unit_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_branch_id'), 'journal_lines', ['branch_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_business_unit_id'), 'journal_lines', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_cost_code_id'), 'journal_lines', ['cost_code_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_department_id'), 'journal_lines', ['department_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_id'), 'journal_lines', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_project_id'), 'journal_lines', ['project_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_tenant_id'), 'journal_lines', ['tenant_id'], unique=False)
    op.create_table('subcontracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('subcontract_number', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('retention_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontracts_tenant_id'), 'subcontracts', ['tenant_id'], unique=False)
    op.create_table('bank_statements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECONCILING', 'RECONCILED', name='bankstatementstatus', native_enum=False), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statements_tenant_id'), 'bank_statements', ['tenant_id'], unique=False)
    op.create_table('client_change_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', name='change_order_status_enum'), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_change_orders_tenant_id'), 'client_change_orders', ['tenant_id'], unique=False)
    op.create_table('client_payment_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('accounting_period_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gross_work', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('previous_certified_work', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('advance_recovery_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('deductions_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adjustments_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_amount_due', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'PAID', name='payment_app_status_enum'), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['accounting_period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_payment_applications_tenant_id'), 'client_payment_applications', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.Enum('AP_PAYMENT', 'AR_RECEIPT', name='paymenttype', native_enum=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'VOID', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('subcontract_change_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subcontract_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', name='sc_change_order_status_enum'), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontract_change_orders_tenant_id'), 'subcontract_change_orders', ['tenant_id'], unique=False)
    op.create_table('subcontract_payment_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subcontract_id', sa.Uuid(), nullable=False),
    sa.Column('accounting_period_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gross_work', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('previous_certified_work', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('advance_recovery_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('deductions_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adjustments_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_amount_due', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'POSTED', 'PAID', name='sc_payment_app_status_enum'), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['accounting_period_id'], ['accounting_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontract_payment_applications_tenant_id'), 'subcontract_payment_applications', ['tenant_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='banktransactiontype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_tenant_id'), 'bank_transactions', ['tenant_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('ap_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('ar_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['ap_invoice_id'], ['ap_invoices.id'], ),
    sa.ForeignKeyConstraint(['ar_invoice_id'], ['ar_invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_tenant_id'), 'payment_allocations', ['tenant_id'], unique=False)
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('bank_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_lines_tenant_id'), 'bank_statement_lines', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_project_forecasts_project_id'), table_name='project_forecasts')
    op.drop_table('project_forecasts')
    op.drop_index(op.f('ix_inventory_adjustment_lines_inventory_adjustment_id'), table_name='inventory_adjustment_lines')
    op.drop_index(op.f('ix_inventory_adjustment_lines_material_id'), table_name='inventory_adjustment_lines')
    op.drop_index(op.f('ix_inventory_adjustment_lines_tenant_id'), table_name='inventory_adjustment_lines')
    op.drop_table('inventory_adjustment_lines')
    op.drop_index(op.f('ix_inventory_adjustments_adjustment_number'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_date'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_status'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_tenant_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_warehouse_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_project_forecast_lines_cost_code_id'), table_name='project_forecast_lines')
    op.drop_index(op.f('ix_project_forecast_lines_forecast_id'), table_name='project_forecast_lines')
    op.drop_table('project_forecast_lines')
    op.alter_column('accounting_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('accounting_periods', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'boqs', 'boq_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('currencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('currencies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'estimates', 'estimate_revisions', ['current_revision_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('fiscal_years', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('fiscal_years', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('goods_receipt_lines', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('goods_receipt_lines', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('goods_receipt_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('goods_receipt_lines_created_by_id_fkey'), 'goods_receipt_lines', type_='foreignkey')
    op.drop_constraint(op.f('goods_receipt_lines_updated_by_id_fkey'), 'goods_receipt_lines', type_='foreignkey')
    op.drop_column('goods_receipt_lines', 'created_by_id')
    op.drop_column('goods_receipt_lines', 'updated_by_id')
    op.add_column('goods_receipts', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('goods_receipts', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('goods_receipts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('goods_receipts_updated_by_id_fkey'), 'goods_receipts', type_='foreignkey')
    op.drop_constraint(op.f('goods_receipts_created_by_id_fkey'), 'goods_receipts', type_='foreignkey')
    op.drop_column('goods_receipts', 'created_by_id')
    op.drop_column('goods_receipts', 'updated_by_id')
    op.add_column('inventory_balances', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('inventory_balances', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('inventory_balances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('inventory_balances_created_by_id_fkey'), 'inventory_balances', type_='foreignkey')
    op.drop_constraint(op.f('inventory_balances_updated_by_id_fkey'), 'inventory_balances', type_='foreignkey')
    op.drop_column('inventory_balances', 'created_by_id')
    op.drop_column('inventory_balances', 'updated_by_id')
    op.add_column('inventory_transactions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('inventory_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('inventory_transactions_created_by_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transactions_updated_by_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'created_by_id')
    op.drop_column('inventory_transactions', 'updated_by_id')
    op.add_column('inventory_transfer_lines', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('inventory_transfer_lines', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('inventory_transfer_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('inventory_transfer_lines_created_by_id_fkey'), 'inventory_transfer_lines', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transfer_lines_updated_by_id_fkey'), 'inventory_transfer_lines', type_='foreignkey')
    op.drop_column('inventory_transfer_lines', 'created_by_id')
    op.drop_column('inventory_transfer_lines', 'updated_by_id')
    op.add_column('inventory_transfers', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('inventory_transfers', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('inventory_transfers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('inventory_transfers_updated_by_id_fkey'), 'inventory_transfers', type_='foreignkey')
    op.drop_constraint(op.f('inventory_transfers_created_by_id_fkey'), 'inventory_transfers', type_='foreignkey')
    op.drop_column('inventory_transfers', 'created_by_id')
    op.drop_column('inventory_transfers', 'updated_by_id')
    op.add_column('material_issue_lines', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('material_issue_lines', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('material_issue_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('material_issue_lines_updated_by_id_fkey'), 'material_issue_lines', type_='foreignkey')
    op.drop_constraint(op.f('material_issue_lines_created_by_id_fkey'), 'material_issue_lines', type_='foreignkey')
    op.drop_column('material_issue_lines', 'created_by_id')
    op.drop_column('material_issue_lines', 'updated_by_id')
    op.add_column('material_issues', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('material_issues', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('material_issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('material_issues_created_by_id_fkey'), 'material_issues', type_='foreignkey')
    op.drop_constraint(op.f('material_issues_updated_by_id_fkey'), 'material_issues', type_='foreignkey')
    op.drop_column('material_issues', 'created_by_id')
    op.drop_column('material_issues', 'updated_by_id')
    op.add_column('materials', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('materials', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('materials_created_by_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_updated_by_id_fkey'), 'materials', type_='foreignkey')
    op.drop_column('materials', 'created_by_id')
    op.drop_column('materials', 'updated_by_id')
    op.alter_column('tenant_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tenant_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('warehouses', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('warehouses', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('warehouses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_warehouses_type'), 'warehouses', ['type'], unique=False)
    op.drop_constraint(op.f('warehouses_updated_by_id_fkey'), 'warehouses', type_='foreignkey')
    op.drop_constraint(op.f('warehouses_created_by_id_fkey'), 'warehouses', type_='foreignkey')
    op.drop_column('warehouses', 'created_by_id')
    op.drop_column('warehouses', 'updated_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('warehouses', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('warehouses_created_by_id_fkey'), 'warehouses', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('warehouses_updated_by_id_fkey'), 'warehouses', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_warehouses_type'), table_name='warehouses')
    op.alter_column('warehouses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('warehouses', 'updated_by')
    op.drop_column('warehouses', 'created_by')
    op.alter_column('tenant_settings', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tenant_settings', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('materials', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('materials', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('materials_updated_by_id_fkey'), 'materials', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('materials_created_by_id_fkey'), 'materials', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('materials', 'updated_by')
    op.drop_column('materials', 'created_by')
    op.add_column('material_issues', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('material_issues', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('material_issues_updated_by_id_fkey'), 'material_issues', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('material_issues_created_by_id_fkey'), 'material_issues', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('material_issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('material_issues', 'updated_by')
    op.drop_column('material_issues', 'created_by')
    op.add_column('material_issue_lines', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('material_issue_lines', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('material_issue_lines_created_by_id_fkey'), 'material_issue_lines', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('material_issue_lines_updated_by_id_fkey'), 'material_issue_lines', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('material_issue_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('material_issue_lines', 'updated_by')
    op.drop_column('material_issue_lines', 'created_by')
    op.add_column('inventory_transfers', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_transfers', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transfers_created_by_id_fkey'), 'inventory_transfers', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inventory_transfers_updated_by_id_fkey'), 'inventory_transfers', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_transfers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_transfers', 'updated_by')
    op.drop_column('inventory_transfers', 'created_by')
    op.add_column('inventory_transfer_lines', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_transfer_lines', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transfer_lines_updated_by_id_fkey'), 'inventory_transfer_lines', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inventory_transfer_lines_created_by_id_fkey'), 'inventory_transfer_lines', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_transfer_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_transfer_lines', 'updated_by')
    op.drop_column('inventory_transfer_lines', 'created_by')
    op.add_column('inventory_transactions', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_transactions', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_transactions_updated_by_id_fkey'), 'inventory_transactions', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inventory_transactions_created_by_id_fkey'), 'inventory_transactions', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_transactions', 'updated_by')
    op.drop_column('inventory_transactions', 'created_by')
    op.add_column('inventory_balances', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_balances', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_balances_updated_by_id_fkey'), 'inventory_balances', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inventory_balances_created_by_id_fkey'), 'inventory_balances', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_balances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('inventory_balances', 'updated_by')
    op.drop_column('inventory_balances', 'created_by')
    op.add_column('goods_receipts', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('goods_receipts', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('goods_receipts_created_by_id_fkey'), 'goods_receipts', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('goods_receipts_updated_by_id_fkey'), 'goods_receipts', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('goods_receipts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('goods_receipts', 'updated_by')
    op.drop_column('goods_receipts', 'created_by')
    op.add_column('goods_receipt_lines', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('goods_receipt_lines', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('goods_receipt_lines_updated_by_id_fkey'), 'goods_receipt_lines', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('goods_receipt_lines_created_by_id_fkey'), 'goods_receipt_lines', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('goods_receipt_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('goods_receipt_lines', 'updated_by')
    op.drop_column('goods_receipt_lines', 'created_by')
    op.alter_column('fiscal_years', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('fiscal_years', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.alter_column('currencies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('currencies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'boqs', type_='foreignkey')
    op.alter_column('accounting_periods', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('accounting_periods', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('project_forecast_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('forecast_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cost_code_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('etc_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], name=op.f('project_forecast_lines_cost_code_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['forecast_id'], ['project_forecasts.id'], name=op.f('project_forecast_lines_forecast_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_forecast_lines_pkey'))
    )
    op.create_index(op.f('ix_project_forecast_lines_forecast_id'), 'project_forecast_lines', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_project_forecast_lines_cost_code_id'), 'project_forecast_lines', ['cost_code_id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adjustment_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'POSTED', 'CANCELLED', name='inventoryadjustmentstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('inventory_adjustments_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_adjustments_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('inventory_adjustments_updated_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('inventory_adjustments_warehouse_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_adjustments_pkey'))
    )
    op.create_index(op.f('ix_inventory_adjustments_warehouse_id'), 'inventory_adjustments', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_tenant_id'), 'inventory_adjustments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_status'), 'inventory_adjustments', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_date'), 'inventory_adjustments', ['date'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_adjustment_number'), 'inventory_adjustments', ['adjustment_number'], unique=False)
    op.create_table('inventory_adjustment_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inventory_adjustment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adjustment_type', postgresql.ENUM('IN', 'OUT', name='adjustmenttype'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('inventory_adjustment_lines_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_adjustment_id'], ['inventory_adjustments.id'], name=op.f('inventory_adjustment_lines_inventory_adjustment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('inventory_adjustment_lines_material_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_adjustment_lines_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('inventory_adjustment_lines_updated_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_adjustment_lines_pkey'))
    )
    op.create_index(op.f('ix_inventory_adjustment_lines_tenant_id'), 'inventory_adjustment_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustment_lines_material_id'), 'inventory_adjustment_lines', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustment_lines_inventory_adjustment_id'), 'inventory_adjustment_lines', ['inventory_adjustment_id'], unique=False)
    op.create_table('project_forecasts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('forecast_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_forecasts_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_forecasts_pkey'))
    )
    op.create_index(op.f('ix_project_forecasts_project_id'), 'project_forecasts', ['project_id'], unique=False)
    op.drop_index(op.f('ix_bank_statement_lines_tenant_id'), table_name='bank_statement_lines')
    op.drop_table('bank_statement_lines')
    op.drop_index(op.f('ix_payment_allocations_tenant_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_bank_transactions_tenant_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_subcontract_payment_applications_tenant_id'), table_name='subcontract_payment_applications')
    op.drop_table('subcontract_payment_applications')
    op.drop_index(op.f('ix_subcontract_change_orders_tenant_id'), table_name='subcontract_change_orders')
    op.drop_table('subcontract_change_orders')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_client_payment_applications_tenant_id'), table_name='client_payment_applications')
    op.drop_table('client_payment_applications')
    op.drop_index(op.f('ix_client_change_orders_tenant_id'), table_name='client_change_orders')
    op.drop_table('client_change_orders')
    op.drop_index(op.f('ix_bank_statements_tenant_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_subcontracts_tenant_id'), table_name='subcontracts')
    op.drop_table('subcontracts')
    op.drop_index(op.f('ix_journal_lines_tenant_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_project_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_journal_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_department_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_cost_code_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_business_unit_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_branch_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_bank_accounts_tenant_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_ar_invoice_lines_tenant_id'), table_name='ar_invoice_lines')
    op.drop_table('ar_invoice_lines')
    op.drop_index(op.f('ix_ap_invoice_lines_tenant_id'), table_name='ap_invoice_lines')
    op.drop_table('ap_invoice_lines')
    op.drop_index(op.f('ix_ar_invoices_tenant_id'), table_name='ar_invoices')
    op.drop_table('ar_invoices')
    op.drop_index(op.f('ix_ap_invoices_tenant_id'), table_name='ap_invoices')
    op.drop_table('ap_invoices')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_chart_of_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_journals_tenant_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_status'), table_name='journals')
    op.drop_index(op.f('ix_journals_date'), table_name='journals')
    op.drop_table('journals')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_chart_of_accounts_tenant_id'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    op.drop_index(op.f('ix_business_units_tenant_id'), table_name='business_units')
    op.drop_index(op.f('ix_business_units_code'), table_name='business_units')
    op.drop_table('business_units')
    # ### end Alembic commands ###
